### ISSUE TITLE
Add link to Doctor Fortran blog?

### ISSUE THREAD

**Issue by sblionel** [fortran-lang/fortran-lang.org#110]
On the Learn page, please add a link under Other Resources > On the Web as follows:

[Doctor Fortran blog](https://stevelionel.com/drfortran) Posts about various aspects, features and misconceptions of the Fortran language

I tried to figure out how to do this myself, but could not locate the source that has the list of links.

**Comment by milancurcic** [comment]
I agree. It needs to be added as an entry [here](https://github.com/fortran-lang/fortran-lang.org/blob/4587a022ea6567968f8a498c0a684e58aa50b8e5/_data/learning.yml#L46).

**Comment by milancurcic** [comment]
Steve, give it a try adding it through a PR, otherwise I can help.

**Comment by sblionel** [comment]
I have never done this before and the help isn't helping. I gather I need to create a branch first, but I never see the option to create a new branch when I type a branch name from the main page. If you can lead me through the steps, I'll give it another go.

**Comment by milancurcic** [comment]
If you use git on your local machine, use this workflow:

1. Navigate to https://github.com/fortran-lang/fortran-lang.org
2. Click on "Fork" in the upper-right corner. This will create a fork of this repository under your account at https://github.com/sblionel/fortran-lang.org.
3. Clone your fork to your local machine:
```
git clone https://github.com/sblionel/fortran-lang.org
```
if you're using username+password to authenticate with GitHub, or:
```
git clone git@github.com:sblionel/fortran-lang.org
```
if you're using an SSH key for a password-less auth.

4. In your local copy of the repo, create and checkout a new branch that will serve for this contribution:

```
cd fortran-lang.org
git branch 110-add-drfortran-blog # creates a new branch with the name 110-add-drfortran-blog
git checkout 110-add-drfortran-blog # switch to the new branch
```

You can name the branch anything you want, but generally it's helpful to put which issue it fixes (110) and a short description in the name.

5. Make changes to `_data/learning.yml` in your local copy.
6. Stage, commit, and push your changes to GitHub:

```
git add _data/learning.yml # this stages the changes in this file
git commit -m "add Dr. Fortran blog entry to the resources" # this commits the change to the repository on your local machine
git push origin 110-add-drfortran-blog # this will push your updated branch to your fork on GitHub at sblionel/fortran-lang.org
```

7. Now navigate to https://github.com/fortran-lang/fortran-lang.org again. Near the top of the page you'll see a yellow box with a suggestion to open a PR with your recent contribution. There will be a button there that says "Compare and open PR" or something similar. Click on it. This will take you to a PR dialog that looks very much like opening a new issue, and you should be good from there.

This approach is tedious and has many steps, but becomes really useful when you need to develop and test on your local machine, and make changes to many files.
----

Alternatively, if you don't use git on your local machine, there is a simpler workflow through GitHub, although I think it's useful only for smaller, single file contributions. For what you want to do here, it should suffice. I am less clear about this approach but I will try.

1. Navigate to https://github.com/fortran-lang/fortran-lang.org/blob/master/_data/learning.yml, that's the file you want to edit.
2. In the upper-right corner, click on the little pencil ("Edit") button. This will take you to the in-browser editor to make changes directly. Because you don't have permissions to write to the file directly, GitHub will automatically create a fork for you, but you don't have to worry about doing anything with it.
3. Once you made the changes, somewhere at the bottom there will be a prompt to open a pull request. This is the part I'm less clear about how it looks exactly because I did this myself only a few times. But the UI should be able to guide you.

Let me know how it goes or if anything's unclear. I recently guided Arjen in #77 to do the same. It seems that it would be useful that we have these notes somewhere prominent on the website, as these steps apply to all projects.

**Comment by milancurcic** [comment]
I realize now that in the first (longer) workflow, you can skip steps 3 through 6, and edit the file in your fork directly on GitHub, then go straight to step 7.

**Comment by sblionel** [comment]
Thanks! I chose the simpler route of doing it through Github, but I will keep this in mind for the future. The UI was straightforward.
