### ISSUE TITLE
Comment text in activity JSON files

### ISSUE THREAD

**Issue by certik** [fortran-lang/fortran-lang.org#129]
Currently we store each comment together with the metadata in the activity JSON files. Do we need to do that? I think the JSON files might become much smaller without the text of the comments. I don't know if we might want to need them in the future, but even if so, I would imagine only to show some statistics (number of words / sentences written?), so it seems to me we can have some separate repository that can store the comments, but the JSON files that we need for this website should only contain things we actually need, which is just the metadata (plus any possible statistics about comments if we want in the future), but not the comments themselves.

**Comment by LKedward** [comment]
Yes you are right, we don't need all the data we are currently storing.
My long term plan has been to perform more pre-processing in the python script before dumping to json; every time the contributor data is loaded on a webpage, the json data has to be processed in javascript ([this function](https://github.com/fortran-lang/fortran-lang.org/blob/ba722c30cf08646bac080370ae301929bb5439c8/assets/js/gh-contributors.js#L273)) to extract a list of contribution dates per user. This is obviously wasteful on the client-side since this processingt can be performed _a priori_.

**Comment by certik** [comment]
Yes, exactly.

**Comment by awvwgk** [comment]
For the new webpage at https://github.com/fortran-lang/webpage we found a solution not requiring to store the JSON data as part of the repository, this issue will therefore be resolved once we migrate to the new page (see #415).
