### ISSUE TITLE
Change title for "Setting up your OS" to "Setting up your Fortran compiler"

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/fortran-lang.org#203]
I think "Setting up your OS" should be renamed "Setting up your Fortran compiler", since it does not discuss something like installing Linux. Also, "developement" should be "development".

**Comment by awvwgk** [comment]
@Beliavsky, feel free to send a patch for these changes.

**Comment by smeskos** [comment]
I would leave the title as is _"Setting up your OS", since to set something up has the meaning to prepare something for use or to be used with something else and not necessarily just to install it, and, of course, in the current context I think by "something" Fortran is implied, at least this is what I had in mind when I wrote it. However, in the explanation below the title, the word _"setup"_ is definitely a mistake since when it is a single word it is a noun and not a verb, I think it can be replaced with _"How to **install a Fortran compiler and set up a development** environment in Windows, Linux and macOS"_. 
Anyway, I am going to wait a couple of days in case there are more opinions/suggestions on the matter and I will submit a new PR with whatever we decide.

**Comment by milancurcic** [comment]
I agree to leave the title as is. Although "Setting up your OS" is a tad too general, the subtitle, visible from the Learn page, is exact and to the point. This mini-book explains more than just setting up the Fortran compiler.
