### ISSUE TITLE
Run failed: Comment on the pull request and push the PR preview to the gh-pages branch - master

### ISSUE THREAD

**Issue by certik** [fortran-lang/fortran-lang.org#298]
Every time I comment on a pull request such as: #295, I get an email with the above title and a link to:

https://github.com/fortran-lang/fortran-lang.org/actions/runs/1086966949

It seems something in the CI is broken.

**Comment by certik** [comment]
I keep getting these emails after every (?) comment I post in this repository. Here is an example:

<img width="840" alt="Screen Shot 2021-09-05 at 6 23 45 PM" src="https://user-images.githubusercontent.com/20568/132145583-5b579008-dc92-423c-b215-0e0a97c77522.png">

First such email is from July 31, 2021. Last one is from a couple minutes ago. So far I got 14 of them.

CC @milancurcic, @awvwgk, @LKedward. Do any of you also get these emails?

**Comment by milancurcic** [comment]
So far I believe I got only 2, but I may have only written 2 comments. Let's see if I get one for this comment.

**Comment by milancurcic** [comment]
Yes, I just got another one. This started with the merging of #297.

**Comment by certik** [comment]
I dread to post another comment, as I will get another email. Thanks @milancurcic for confirming. Yes, it looks like #297 caused it, so that should help in figuring out a fix.

**Comment by awvwgk** [comment]
> Do any of you also get these emails?

No, I reduced my GitHub notification emails to the absolute minimum and I'm still getting like ~50 a day. Failing job emails are like 100% noise in my inbox.

The issue is that the two-stage workflow for building the build preview will trigger on every comment event in this repository. The first stage will skip if the required phase is not part of the comment body. But apparently the second phase will always trigger regardless. It either has to check the comment body as well and skip, only get triggered on successful first phase or be able to fail gracefully.

This check stops workflows from running in the first phase:

https://github.com/fortran-lang/fortran-lang.org/blob/66ed1d4f35b01c01ec54d9494d2e9de5980ae0c1/.github/workflows/buildPRPreview.yml#L22

While the event used here does in fact always evaluate to a truthy value

https://github.com/fortran-lang/fortran-lang.org/blob/66ed1d4f35b01c01ec54d9494d2e9de5980ae0c1/.github/workflows/commentAndPushPRPreview.yml#L24-L26

**Comment by awvwgk** [comment]
Please checkout the preview workflow on the new repository, this seems to be resolved there.
