### ISSUE TITLE
Twitter feed on the site -- watch the language

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/fortran-lang.org#352]
Looking at the tweets displayed on the site, I currently see the one below. It's ok for Twitter, but given the language, I think it makes the fortran-lang site seem less serious and professional. Is it possible to only display tweets on the site that pass a language filter? If not, the people behind @fortranlang should considering more judicious about what is retweeted.

I hope I don't sound too stuffy. The tweet and thread were funny and harmless, but I don't they match the tone of the web site.

Fortran Retweeted

Dr. Héloïse Stevance 🖤✨
@Sydonahi
Holy fuck Fortran is fast but I didn't know HOW fast. 

Generated 1 million values in 4 nested for loops (do loops), thought it'd take a couple minutes.. DID IT UNDER 2 SECONDS WTF

**Comment by milancurcic** [comment]
I agree, we shouldn't have such language on the site.

Before retweeting, I had a pause for the same reason. I decided that the potential pros outweighed the potential cons, so I did it. I did forget that we also show the feed on the language page, which is problematic in a situation like this.

Going forward, we can agree to simply not RT any such language, even of it may be beneficial (e.g. this RT brought us ~20 new followers).

Or, we can remove the feed from the site, and only provide a link to the Twitter feed.

**Comment by certik** [comment]
I fixed this by retweeting some nice tweet, so now I see this:

<img width="457" alt="Screen Shot 2021-12-16 at 4 30 49 PM" src="https://user-images.githubusercontent.com/20568/146479302-0b063c28-01b7-49c8-bbd6-927191516785.png">

So that should work.

Yes, I am not happy with the quality of interactions at Twitter in general, but it is the most effective social media right now, so I think it can bring us some good new users. I know it did. I don't know why this particular tweet generated such attention, but it did. So maybe next time we can retweet, and then retweet some other tweets, so that it is not the top 2 tweets, and then it does not appear at the front page.

**Comment by milancurcic** [comment]
> I don't know why this particular tweet generated such attention, but it did.

I think because the account has 22.7k followers. It's powerful.

**Comment by ivan-pi** [comment]
The person behind the tweet (@HeloiseS) is a [computational astronomer](https://www.hfstevance.com/research).

Amusingly, many of the responses to her tweet use the uppercase form FORTRAN, and even some examples of implicit typing. Goes to show how deeply entrenched these obsolescent forms are... Immediately after comes a backlash of responses citing equivalent or better performance with Python + Numba, or Julia. 

Overall, I agree not to retweet in case of vulgar language, but think we've learned a valuable lesson from this tweet. Personally, I like the Twitter feed on the front page. I'm not an active Twitter user, but I enjoy seeing some of the tweets.

**Comment by HeloiseS** [comment]
Hello everybody! 

Since I'm the original poster I thought I'd add my 2cent, especially regarding certain types of language on twitter and other platforms and why that tweet got so much traction on social media. 

Twitter interactions are powerful because they walk a weird line between profession and personal content. Being informal and personable in a tweet is likely to drive interactions; using emotive language to share excitement (in this case) is an unconscious queue for others to join you in something they find exciting, whether it be how fotran is really cool or how numba can be faster in certain cases. It's called *social* media for a reason. 

I understand some people don't use certain types of language, and what you choose to display on your cite is your prerogative (the solution of quickly RT a couple other tweets is a smart one), but I do want to bring up the fact that casual swearing is less to do with professionalism and more to do with cultural norms in terms of geography, nationality and, to some extent, generation and class. Overall, blanket rules against swearing are rarely helpful and often at the disservice of minority groups (although it may not be the intention) - besides, one can be plenty disrespectful without 4-letter words. Maybe ensuring that the message reflects a spirit of congeniality is a better focus. 

Final point, as someone who does know a fair bit about social media, I wouldn't recommend trying to seem too formal. Fortran's image isn't exactly that of silly goofy tool - if anything the very dry and stoic image might be limiting the interest you'll get from young millennials and gen z who have a different experience of how brands represent themselves (check the duo lingo or Ryanair Tik tok accounts) and expect a more personable, less serious approach. As for the older folks? I think it's safe to say they won't stop using Fortran if you start tweeting memes some day ;)

Hope this could bring some new perspectives.

**Comment by Beliavsky** [comment]
On the general subject of Twitter, I follow @SciPyTip , which has 131.4K Followers (including me) and which provides tips such as

"np.ones() returns an array of specified shape filled with 1's. np.zeros() does the same but filled with 0's."

I guess falling attention spans have created demand for information in small quantities. Motivated by this, I just created @Fortrantip and tweeted some very basic things such as Hello World program and a demonstration of a do loop.

**Comment by milancurcic** [comment]
Thanks a lot for writing here, @HeloiseS, and good points which I agree with.

Your tweet was obviously not meant as disrespectful (and that's why I chose to RT it), though I see how a word can be offensive to some regardless of the context. We can't possibly make everybody happy all the time, but we do our best and continuously learn and adjust course to make most people happy most of the time. Though I don't like blanket rules, they may help with nuanced situations and avoiding to spend time on discussing whether something is appropriate or not. If not the best solution, avoiding such language for us may be the easiest solution for now.

Re: formality and dryness that is pervasive in Fortran, I actively work to change this image and to make it attractive to younger audiences. It's possible to brand something dry, formal, and standard like Fortran as something that's also fun and playful.

**Comment by certik** [comment]
Thanks for your feedback @HeloiseS, we appreciate it. I think none of us are offended by swear words. It's more of what kind of an image we want to show, and we've been figuring it out as we go. How to best handle a tweet like yours was new to us. :)

Anyway, thanks for tweeting about Fortran! And if you have any questions, definitely let us know.

**Comment by HeloiseS** [comment]
> I guess falling attention spans have created demand for information in small quantities. Motivated by this, I just created [@Fortrantip](https://twitter.com/fortrantip) on Twitter and tweeted some very basic things such as Hello World program and a demonstration of a do loop.

That is a great idea, and the real issue here isn't falling attention span, it's the exponential increase in content that people can choose from. People's attention is the most valuable currency on the internet and you are competing with thousands and millions or other content creators, which is why short snappy content like that scipy example work well. 

I'll follow that new Fortran account and tag you when I stumble upon tips and tricks I share on my platform :)

**Comment by certik** [comment]
> Edit: @Beliavsky I recommend adding a profile picture, a banner and a slightly more extended description to make the account look legit :)

I saw that you added the same logo as we use for the main Fortran account. I got confused as I mainly look at the logo and I thought it was the main Fortran account tweeting it. Do you think you could please modify the logo? You can perhaps add "t" to the F, or "tip" or some icon or something to make it distinct enough.

**Comment by LKedward** [comment]
> I got confused as I mainly look at the logo and I thought it was the main Fortran account tweeting it.

The same thing happened to me, I thought it was from the Fortran-lang account!
I agree it would be really good if the profile pic could be changed - perhaps even just a simple recoloring of the logo background?

**Comment by awvwgk** [comment]
We still need to establish some guidelines for the usage of the logo and assorted assets (see https://github.com/fortran-lang/fortran-lang.org/issues/342). I don't see an issue with using or adapting the logo or its color for Fortran related projects, but we should give some guidance on this. While I don't see a big issue with using the same logo, I think we should encourage some creative difference in this case.

@Beliavsky I can offer some help with designing an avatar for the FortranTip account, feel free to email or PM me via Discourse and we can create something fitting. I'm really looking forward to establish the fpm color palette around Fortran ;).

**Comment by milancurcic** [comment]
I agree and also recommend changing the @FortranTip logo. If your intent is to communicate that account is related to but different from @fortranlang, then I think changing the background color as @LKedward suggested is best. I suggest some soft (pastel) color, pick any that you like best. Adding "tip" to the logo as @certik suggested would be great, but may be difficult in practice considering the circular shape of Twitter profile pics.

**Comment by Beliavsky** [comment]
I understand the need to avoid confusion with the fortranlang twitter and have changed the logo what @milancurcic linked to: small Fs of various colors. Is that ok?

**Comment by milancurcic** [comment]
@Beliavsky, interesting. It's not what I had in mind (I thought just having a single F, but with a different color), but now that I see this, I kinda like it. Definitely distinct from the @fortranlang logo.
