### ISSUE TITLE
Move the Discourse link at the top

### ISSUE THREAD

**Issue by certik** [fortran-lang/fortran-lang.org#85]
Currently one must scroll down to find the Discourse link. Let's put it at the top horizontal menu? I think we want this as the primary discussion forum, so that would be a great place for it.

**Comment by milancurcic** [comment]
I agree it should be easier to find. I'm not crazy about the Discourse badge being in the navbar, design-wise. But maybe it could work, all the way to the right of "News". The problem here is that on mobile, Discourse link would be hidden until the user opens the sandwich bar. A workaround for this would be to keep the Discourse link both where it is now, and to add it to the navbar.

An alternative would be to move the whole "Join us" section up, and bring the "News" section down. I think this would be my favorite solution.

**Comment by LKedward** [comment]
Yeah I agree, just move the section up. It definitely shouldn't be in the navbar.

**Comment by certik** [comment]
I was thinking putting either "Forum" or "Discourse" into the navigation bar at the top, not the logo. Is there a problem design-wise with that?

**Comment by LKedward** [comment]
We could do something like this where we group our external links (discourse, twitter, github) as mini icons in the navbar far right, separate from internal nav links?
![navbar_social2](https://user-images.githubusercontent.com/26024234/82255914-58d35d80-994d-11ea-8731-88d4d61c1010.PNG)

**Comment by certik** [comment]
@LKedward this looks even better! I just want to go to fortran-lang.org and then get to Discourse from there. I just don't remember the address and ultimately we want more people to do what I do --- to go through the main webpage. So that as we add more things, or announcements, they can see them.

**Comment by LKedward** [comment]
> I just want to go to fortran-lang.org and then get to Discourse from there. I just don't remember the address ..

I've been doing the exact same thing! Scrolling down each time.

>  and ultimately we want more people to do what I do --- to go through the main webpage. So that as we add more things, or announcements, they can see them.

Absolutely I agree, we want this to be more accessible and visible.
I can have a go at putting this together this week 👍
